= Literature Review: Learning by playing Videogames
//Settings:
:icons: font
:toc:

== Abstract

By analysing existing research, this paper wants to find out:

 1. what features make games educative to the player
 1. which teaching methods these features employ
 1. what scientific methods are used to analyse the impact of these features
 1. and what open questions exist in this field of study.

This paper will be continuously updated to give an overview during the process of creation of the document.
Currently, 1 paper was looked at, cite:[StanitsasMariosFstt]. It was used to find one scientific method: the scientific literature review.
Additionally, it helped at building a database of 77 existing games that were considered educative.

== Introduction

There are many areas in which our world needs us to change our ways. Educative games can help by increasing engagement with learning
topics and allowing the players to engage with the topic interactively during learning.

== Research Method

TODO

== Results and Discussion

TODO

== Conclusions

TODO

== Appendix

TODO

[bibliography]
== Bibliography
bibliography::[]
